---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  cookbook_path: berks-cookbooks/

platforms:
  - name: ubuntu-15.04

suites:
  - name: app
    run_list:
    attributes:
  - name: web
    run_list:
      - recipe[nginx::default]
    attributes:
