name             'sainsburys'
maintainer       'Craig Webster'
maintainer_email 'craig@barkingiguana.com'
license          'All rights reserved'
description      'Installs/Configures sainsburys'
long_description 'Installs/Configures sainsburys'
version          '0.1.0'
