name             'sainsburys'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures sainsburys'
long_description 'Installs/Configures sainsburys'
version          '0.1.0'
